steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'eu.gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA','--build-arg=ACCESS_TOKEN=$_ACCESS_TOKEN', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'eu.gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA']

    # Deploy an image from Container Registry to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'beta',
      'run',
      'deploy',
      "${_SERVICE_NAME}",
      '--image', 'eu.gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA',
      '--region', 'europe-west1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--min-instances', '${_MIN_INST}',
      '--max-instances', '${_MAX_INST}',
      '--memory', '${_MEMORY_LIMIT}',
      '--cpu', '${_CPU}',
      '--set-secrets', '/tmp/secrets/.env=${_SECRET_NAME}:latest',
      '--timeout', '59m59s'
  ]

    # Automatically update the traffic to the latest revision
    # This will update the latest revision to serve 100% traffic
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run',
      'services',
      'update-traffic',
      "${_SERVICE_NAME}",
      '--to-latest',
      '--region', 'europe-west1',
      '--platform', 'managed',
  ]

images:
- 'eu.gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA'

timeout: 1200s
queueTtl: 3600s