// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Author struct {
	ID       int    `json:"id"`
	Username string `json:"username"`
}

type ContentItem struct {
	ID               int     `json:"id"`
	Author           *Author `json:"author"`
	Title            string  `json:"title"`
	ShortDescription *string `json:"shortDescription"`
	Body             string  `json:"body"`
	Views            int     `json:"views"`
	Likes            int     `json:"likes"`
	Tags             []*Tag  `json:"tags"`
}

type Tag struct {
	ID   int    `json:"id"`
	Type string `json:"type"`
}
