// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Faq struct {
	Question string `json:"question"`
	Answer   string `json:"answer"`
}

type FeedItem struct {
	Title       string `json:"title"`
	Description string `json:"description"`
}

type LibraryItem struct {
	Title       string `json:"title"`
	Description string `json:"description"`
}
