// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

// EventAttachment is used to serialize Google Calendar event attachments.
type EventAttachment struct {
	FileID   string `json:"fileID"`
	FileURL  string `json:"fileURL"`
	IconLink string `json:"iconLink"`
	MimeType string `json:"mimeType"`
	Title    string `json:"title"`
}

// EventAttendee is used to serialize Google Calendar event attendees.
type EventAttendee struct {
	ID               string `json:"id"`
	AdditionalGuests int    `json:"additionalGuests"`
	Comment          string `json:"comment"`
	DisplayName      string `json:"displayName"`
	Email            string `json:"email"`
	Optional         bool   `json:"optional"`
	Organizer        bool   `json:"organizer"`
	Resource         bool   `json:"resource"`
	ResponseStatus   string `json:"responseStatus"`
	Self             bool   `json:"self"`
}

// EventDateTime is used to serialize Google Calendar event dates and times.
type EventDateTime struct {
	Date     string `json:"date"`
	DateTime string `json:"dateTime"`
	TimeZone string `json:"timeZone"`
}
