# Deploy the browser detector function
steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - ${_FUNCTION_NAME}
  - --region=FUNCTION_REGION
  - --source=.
  - --trigger-http
  - --allow-unauthenticated
  - --region=europe-west3
  - --runtime python38